In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
ages = [20, 22, 25, 27, 21, 23, 37, 31,  61, 45, 41, 32]

In [4]:
bins = [18, 25, 35, 60, 100]

In [5]:
age_categories = pd.cut(ages, bins)

In [6]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [7]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [8]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [9]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [12]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [13]:
marks = [ 30, 54, 69, 100]

In [23]:
bins = [0,45, 70, 100]

In [28]:
marks_categories = pd.cut(marks, bins, labels = ["fail", "pass", "good"])

In [29]:
marks_categories

['fail', 'pass', 'pass', 'good']
Categories (3, str): ['fail' < 'pass' < 'good']

In [30]:
marks_categories.value_counts()

fail    1
pass    2
good    1
Name: count, dtype: int64

In [31]:
pd.cut(marks, bins, right=False)

[[0.0, 45.0), [45.0, 70.0), [45.0, 70.0), NaN]
Categories (3, interval[int64, left]): [[0, 45) < [45, 70) < [70, 100)]

In [32]:
data = np.random.uniform(size = 20)

In [33]:
pd.cut(data, 4, precision =2)

[(0.52, 0.73], (0.091, 0.3], (0.52, 0.73], (0.091, 0.3], (0.3, 0.52], ..., (0.091, 0.3], (0.73, 0.94], (0.3, 0.52], (0.73, 0.94], (0.091, 0.3]]
Length: 20
Categories (4, interval[float64, right]): [(0.091, 0.3] < (0.3, 0.52] < (0.52, 0.73] < (0.73, 0.94]]

In [35]:
data = np.random.standard_normal(1000)

In [36]:
quartiles = pd.qcut(data, 4, precision=2)

In [37]:
quartiles

[(0.68, 3.3], (-3.28, -0.65], (0.68, 3.3], (0.0058, 0.68], (0.0058, 0.68], ..., (-3.28, -0.65], (0.68, 3.3], (-3.28, -0.65], (0.0058, 0.68], (-3.28, -0.65]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.28, -0.65] < (-0.65, 0.0058] < (0.0058, 0.68] < (0.68, 3.3]]

In [38]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.2689999999999997, -1.312]    100
(-1.312, 0.00581]                400
(0.00581, 1.265]                 400
(1.265, 3.301]                   100
Name: count, dtype: int64

In [39]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))

In [40]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.016118,0.005988,0.014933,0.047296
std,1.003375,1.018477,0.987734,0.987969
min,-3.422809,-2.714991,-3.185307,-3.175110
25%,-0.663978,-0.692758,-0.639877,-0.629660
50%,0.009184,0.017907,0.018344,0.012190
75%,0.708608,0.636286,0.663591,0.688432
max,3.051397,3.110251,3.098508,3.295274


In [41]:
col = data[2]

In [42]:
col[col.abs() > 3]

444    3.026330
534   -3.185307
640    3.098508
870    3.095537
Name: 2, dtype: float64

In [43]:
data[(data.abs() > 3).any(axis = "columns")]

,0,1,2,3
219,0.663816,0.532472,0.762217,3.295274
232,0.084475,3.074116,-1.030696,0.376313
407,3.051397,1.665527,0.919413,-0.470520
444,-2.003805,1.388677,3.026330,-1.622417
534,0.471586,0.100695,-3.185307,0.194253
573,0.820157,3.110251,-0.087209,-0.905341
640,-0.403814,-1.900208,3.098508,-0.649168
870,0.822138,0.390641,3.095537,-2.275825
888,-3.422809,-0.535926,0.544566,-0.552174
921,1.732752,-0.178374,0.949251,-3.175110


In [44]:
data[data.abs()>3] = np.sign(data)*3

In [45]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.016490,0.005803,0.014898,0.047176
std,1.001858,1.017926,0.986473,0.986484
min,-3.000000,-2.714991,-3.000000,-3.000000
25%,-0.663978,-0.692758,-0.639877,-0.629660
50%,0.009184,0.017907,0.018344,0.012190
75%,0.708608,0.636286,0.663591,0.688432
max,3.000000,3.000000,3.000000,3.000000


In [46]:
np.sign(data).head()

,0,1,2,3
0,-1.0,1.0,1.0,1.0
1,1.0,1.0,-1.0,-1.0
2,1.0,1.0,1.0,1.0
3,-1.0,1.0,-1.0,1.0
4,1.0,1.0,-1.0,-1.0


In [47]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [48]:
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [49]:
sampler = np.random.permutation(5)

In [50]:
sampler

array([3, 2, 0, 1, 4], dtype=int32)

In [51]:
df.take(sampler)

,0,1,2,3,4,5,6
3,21,22,23,24,25,26,27
2,14,15,16,17,18,19,20
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
4,28,29,30,31,32,33,34


In [52]:
df.iloc[sampler]

,0,1,2,3,4,5,6
3,21,22,23,24,25,26,27
2,14,15,16,17,18,19,20
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
4,28,29,30,31,32,33,34


In [53]:
column_sampler = np.random.permutation(7)

In [54]:
column_sampler

array([3, 1, 2, 5, 4, 0, 6], dtype=int32)

In [55]:
df.take(column_sampler, axis = "columns")

,3,1,2,5,4,0,6
0,3,1,2,5,4,0,6
1,10,8,9,12,11,7,13
2,17,15,16,19,18,14,20
3,24,22,23,26,25,21,27
4,31,29,30,33,32,28,34


In [56]:
df.sample(n=3)

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27


In [57]:
choices = pd.Series([5,7,-1,6,4])

In [58]:
choices.sample(n=10, replace = True)

1    7
3    6
2   -1
2   -1
4    4
1    7
2   -1
1    7
0    5
2   -1
dtype: int64