In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr = np.arange(12).reshape((3,4))

In [4]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.concatenate([arr, arr], axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [6]:
np.concatenate([arr, arr], axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
s1 = pd.Series([0,1], index = ["a", "b"], dtype = "Int64")

In [8]:
s2 = pd.Series([2,3,4], index = ["c", "d", "e"], dtype = "Int64")

In [9]:
s3 = pd.Series([5, 6], index = ["f", "g"], dtype = "Int64")

In [10]:
s1 

a    0
b    1
dtype: Int64

In [11]:
s2

c    2
d    3
e    4
dtype: Int64

In [12]:
s3

f    5
g    6
dtype: Int64

In [16]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [17]:
pd.concat([s1,s2,s3], axis = 1)

,0,1,2
a,0,<NA>,<NA>
b,1,<NA>,<NA>
c,<NA>,2,<NA>
d,<NA>,3,<NA>
e,<NA>,4,<NA>
f,<NA>,<NA>,5
g,<NA>,<NA>,6


In [19]:
s4 = pd.concat([s1,s3])

In [20]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [21]:
pd.concat([s1,s4], axis = 1)

,0,1
a,0,0
b,1,1
f,<NA>,5
g,<NA>,6


In [22]:
pd.concat([s1,s4], axis=1, join="inner")

,0,1
a,0,0
b,1,1


In [27]:
result = pd.concat([s1,s1,s3],keys = ["one", "two", "three"])

In [25]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [28]:
result.unstack()

,a,b,f,g
one,0,1,<NA>,<NA>
two,0,1,<NA>,<NA>
three,<NA>,<NA>,5,6


In [29]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), index = ["a", "b", "c"], columns= ["one", "two"])

In [30]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2,2), index=["a", "c"], columns=["three", "four"])

In [31]:
df1

,one,two
a,0,1
b,2,3
c,4,5


In [32]:
df2

,three,four
a,5,6
c,7,8


In [33]:
pd.concat([df1, df2], axis=1, keys=["level1", "level2"])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0